#!/bin/bash

function __fetch_infovis__ {
	bin/fetch_infovis.sh $DATASET_PATH
	CORPUS_PATH=$DATASET_PATH/corpus/infovis-papers.txt
	META_PATH=$DATASET_PATH/corpus/infovis-papers-meta.txt
}

function __fetch_20newsgroups__ {
	bin/fetch_20newsgroups.sh $DATASET_PATH
	CORPUS_PATH=$DATASET_PATH/corpus
}

function __fetch_nsf127992__ {
	bin/fetch_nsf127992.sh $DATASET_PATH
	CORPUS_PATH=$DATASET_PATH/corpus/nsf127992.txt
}

function __fetch_nsf25k__ {
	bin/fetch_nsf25k.py $DATASET_PATH
	CORPUS_PATH=$DATASET_PATH/corpus/nsf25k.txt
}

function __fetch_nsf10k__ {
	bin/fetch_nsf10k.py $DATASET_PATH
	CORPUS_PATH=$DATASET_PATH/corpus/nsf10k.txt
}

function __fetch_nsf1k__ {
	bin/fetch_nsf1k.py $DATASET_PATH
	CORPUS_PATH=$DATASET_PATH/corpus/nsf1k.txt
}

function __fetch_poliblogs__ {
	bin/fetch_poliblogs.sh $DATASET_PATH
	CORPUS_PATH=$DATASET_PATH/corpus/poliblogs2008.txt
	META_PATH=$DATASET_PATH/corpus/poliblogs2008-meta.txt
}

function __train_mallet__ {
	bin/setup_mallet.sh
	echo "# Training a MALLET LDA topic model..."
	echo "bin/train_mallet.sh $CORPUS_PATH $MODEL_PATH"
	echo
	bin/train_mallet.sh $CORPUS_PATH $MODEL_PATH
	echo
}

function __import_mallet__ {
	echo "# Importing a MALLET LDA topic model..."
	echo "bin/import_mallet.py $APP_IDENTIFIER $MODEL_PATH"
	echo
	bin/import_mallet.py $APP_IDENTIFIER $MODEL_PATH
	echo
	if [ "$META_PATH" == "NONE" ]
	then
		echo "bin/import_corpus.py $APP_IDENTIFIER --terms $MODEL_PATH/corpus.mallet"
		echo
		bin/import_corpus.py $APP_IDENTIFIER --terms $MODEL_PATH/corpus.mallet
	else
		echo "bin/import_corpus.py $APP_IDENTIFIER --terms $MODEL_PATH/corpus.mallet --meta $META_PATH"
		echo
		bin/import_corpus.py $APP_IDENTIFIER --terms $MODEL_PATH/corpus.mallet --meta $META_PATH
	fi
	echo
}

function __train_treetm__ {
	bin/setup_treetm.sh
	echo "# Training a TreeTM model..."
	echo "bin/train_treetm.py $CORPUS_PATH $MODEL_PATH"
	echo
	bin/train_treetm.py $CORPUS_PATH $MODEL_PATH
	echo
}

function __import_treetm__ {
	echo "# Importing a TreeTM model..."
	echo "bin/import_treetm.py $APP_IDENTIFIER $MODEL_PATH"
	echo
	bin/import_treetm.py $APP_IDENTIFIER $MODEL_PATH
	echo
	if [ "$META_PATH" == "NONE" ]
	then
		echo "bin/import_corpus.py $APP_IDENTIFIER --terms $MODEL_PATH/corpus.mallet"
		echo
		bin/import_corpus.py $APP_IDENTIFIER --terms $MODEL_PATH/corpus.mallet
	else
		echo "bin/import_corpus.py $APP_IDENTIFIER --terms $MODEL_PATH/corpus.mallet --meta $META_PATH"
		echo
		bin/import_corpus.py $APP_IDENTIFIER --terms $MODEL_PATH/corpus.mallet --meta $META_PATH
	fi
	echo
}

function __train_stm__ {
	bin/setup_stm.sh
	echo "# Training a Structural Topic Model..."
	echo "bin/train_stm.py $CORPUS_PATH $MODEL_PATH"
	echo
	bin/train_stm.py $CORPUS_PATH $MODEL_PATH
	echo
}

function __import_stm__ {
	echo "# Importing a Structural Topic Model..."
	echo "bin/import_stm.py $APP_IDENTIFIER $MODEL_PATH"
	echo
#	bin/import_stm.py $APP_IDENTIFIER $MODEL_PATH
	bin/import_stm.py $APP_IDENTIFIER $DATASET_PATH/corpus/poliblogs2008.RData

	echo
	if [ "$META_PATH" == "NONE" ]
	then
		echo "bin/import_corpus.py $APP_IDENTIFIER"
		echo
		bin/import_corpus.py $APP_IDENTIFIER
	else
		echo "bin/import_corpus.py $APP_IDENTIFIER --meta $META_PATH"
		echo
		bin/import_corpus.py $APP_IDENTIFIER --meta $META_PATH
	fi
	echo
}

function __train_stmt__ {
	bin/setup_stmt.sh
	echo "# Training a STMT model..."
	echo "bin/train_stmt.py $CORPUS_PATH $MODEL_PATH"
	echo
	bin/train_stmt.py $CORPUS_PATH $MODEL_PATH
	echo
}

function __import_stmt__ {
	echo "# Importing a STMT model..."
	echo "bin/import_stmt.py $APP_IDENTIFIER $MODEL_PATH"
	echo
	bin/import_stmt.py $APP_IDENTIFIER $MODEL_PATH
	echo
	if [ "$META_PATH" == "NONE" ]
	then
		echo "bin/import_corpus.py $APP_IDENTIFIER"
		echo
		bin/import_corpus.py $APP_IDENTIFIER
	else
		echo "bin/import_corpus.py $APP_IDENTIFIER --meta $META_PATH"
		echo
		bin/import_corpus.py $APP_IDENTIFIER --meta $META_PATH
	fi
	echo
}

function __train_gensim__ {
	bin/setup_gensim.sh
	echo "# Training a gensim LDA topic model..."
	echo "bin/train_gensim.py $CORPUS_PATH $MODEL_PATH"
	echo
	bin/train_gensim.py $CORPUS_PATH $MODEL_PATH --passes 10
	echo
}

function __import_gensim__ {
	echo "# Importing a gensim LDA topic model..."
	echo "bin/import_gensim.py $APP_IDENTIFIER $MODEL_PATH/corpus.dict $MODEL_PATH/output.model"
	echo
	bin/import_gensim.py $APP_IDENTIFIER $MODEL_PATH/corpus.dict $MODEL_PATH/output.model
	echo
	if [ "$META_PATH" == "NONE" ]
	then
		echo "bin/import_corpus.py $APP_IDENTIFIER"
		echo
		bin/import_corpus.py $APP_IDENTIFIER
	else
		echo "bin/import_corpus.py $APP_IDENTIFIER --meta $META_PATH"
		echo
		bin/import_corpus.py $APP_IDENTIFIER --meta $META_PATH
	fi
}

if [ $# -ge 1 ] && [ "$1" != "-h" ] && [ "$1" != "--help" ]
then
	DATASET=$1
	if [ "$DATASET" == "infovis" ] || [ "$DATASET" == "20newsgroups" ] || [ "$DATASET" == "nsf127992" ] || [ "$DATASET" == "nsf25k" ] || [ "$DATASET" == "nsf10k" ] || [ "$DATASET" == "nsf1k" ] || [ "$DATASET" == "poliblogs" ]
	then
		FETCH_DATASET_FUNCTION=__fetch_${DATASET}__
		DATASET_PATH=data/demo/$DATASET
		CORPUS_PATH="NONE"
		META_PATH="NONE"
		if [ $# -ge 2 ]
		then
			MODEL=$2
		else
			MODEL="mallet"
		fi
		if [ "$MODEL" == "mallet" ] || [ "$MODEL" == "treetm" ] || [ "$MODEL" == "stmt" ] || [ "$MODEL" == "stm" ] || [ "$MODEL" == "gensim" ]
		then
			TRAIN_MODEL_FUNCTION=__train_${MODEL}__
			IMPORT_MODEL_FUNCTION=__import_${MODEL}__
			MODEL_PATH=$DATASET_PATH/model-$MODEL
			APP_IDENTIFIER=${DATASET}_${MODEL}

			bin/setup_web2py.sh
			$FETCH_DATASET_FUNCTION
			$TRAIN_MODEL_FUNCTION
			$IMPORT_MODEL_FUNCTION
			exit 0
		fi
	fi
fi

echo "Usage: $0 dataset model"
echo
echo "Available datasets:"
echo "      infovis | IEEE InfoVis Proceedings from 1995 to 2011"
echo "              | 449 paper abstracts with title, authors, year"
echo
echo " 20newsgroups | User postings in 20 newsgroups"
echo "              | 18,828 postings with duplicates removed"
echo "              | http://qwone.com/~jason/20Newsgroups"
echo
echo "    nsf127992 | NSF grants"
echo "              | 127,992 abstracts"
echo
echo "    poliblogs | Poliblogs"
echo "              | 13,246 political blogs with date, rating, political affiliation"
echo
echo "Available models:"
echo "       mallet | MAchine Learning for LanguagE Toolkit (MALLET)"
echo "              | Default topic model if none is specified"
echo "              | http://mallet.cs.umass.edu"
echo
echo "       treetm | Efficient Tree-based Topic Modeling"
echo "              | http://www.cs.umd.edu/~ynhu"
echo
echo "         stmt | Stanford Topic Modeling Toolbox"
echo "              | http://nlp.stanford.edu/downloads/tmt"
echo
echo "          stm | Structural Topic Models"
echo "              | Requires R"
echo "              | http://structuraltopicmodel.com"
echo
echo "       gensim | Gensim"
echo "              | Requires numpy and scipy"
echo "              | http://radimrehurek.com/gensim/"
echo
