# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='wordnet_file.proto',
  package='topicmod_projects_ldawn',
  serialized_pb='\n\x12wordnet_file.proto\x12\x17topicmod_projects_ldawn\"\xb6\x03\n\x0bWordNetFile\x12<\n\x07synsets\x18\x01 \x03(\x0b\x32+.topicmod_projects_ldawn.WordNetFile.Synset\x12\x0c\n\x04root\x18\x02 \x02(\x05\x1a\xda\x02\n\x06Synset\x12\x0e\n\x06offset\x18\x01 \x02(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x18\n\x10\x63hildren_offsets\x18\x03 \x03(\r\x12\x11\n\traw_count\x18\x04 \x01(\x01\x12\x15\n\rhyponym_count\x18\x05 \x01(\x01\x12?\n\x05words\x18\x06 \x03(\x0b\x32\x30.topicmod_projects_ldawn.WordNetFile.Synset.Word\x12\x16\n\x0ehyperparameter\x18\x07 \x01(\t\x1a\x95\x01\n\x04Word\x12\x0f\n\x07term_id\x18\x01 \x02(\r\x12\x12\n\x07lang_id\x18\x02 \x01(\r:\x01\x30\x12\x10\n\x08term_str\x18\x03 \x02(\t\x12\x10\n\x08lang_str\x18\x04 \x01(\t\x12\x12\n\nx_location\x18\x05 \x01(\x01\x12\x12\n\ny_location\x18\x06 \x01(\x01\x12\r\n\x05\x64\x65pth\x18\x07 \x01(\x05\x12\r\n\x05\x63ount\x18\x08 \x01(\x01')




_WORDNETFILE_SYNSET_WORD = descriptor.Descriptor(
  name='Word',
  full_name='topicmod_projects_ldawn.WordNetFile.Synset.Word',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='term_id', full_name='topicmod_projects_ldawn.WordNetFile.Synset.Word.term_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lang_id', full_name='topicmod_projects_ldawn.WordNetFile.Synset.Word.lang_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='term_str', full_name='topicmod_projects_ldawn.WordNetFile.Synset.Word.term_str', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lang_str', full_name='topicmod_projects_ldawn.WordNetFile.Synset.Word.lang_str', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='x_location', full_name='topicmod_projects_ldawn.WordNetFile.Synset.Word.x_location', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y_location', full_name='topicmod_projects_ldawn.WordNetFile.Synset.Word.y_location', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='depth', full_name='topicmod_projects_ldawn.WordNetFile.Synset.Word.depth', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='topicmod_projects_ldawn.WordNetFile.Synset.Word.count', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=337,
  serialized_end=486,
)

_WORDNETFILE_SYNSET = descriptor.Descriptor(
  name='Synset',
  full_name='topicmod_projects_ldawn.WordNetFile.Synset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='offset', full_name='topicmod_projects_ldawn.WordNetFile.Synset.offset', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key', full_name='topicmod_projects_ldawn.WordNetFile.Synset.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='children_offsets', full_name='topicmod_projects_ldawn.WordNetFile.Synset.children_offsets', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='raw_count', full_name='topicmod_projects_ldawn.WordNetFile.Synset.raw_count', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hyponym_count', full_name='topicmod_projects_ldawn.WordNetFile.Synset.hyponym_count', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='words', full_name='topicmod_projects_ldawn.WordNetFile.Synset.words', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hyperparameter', full_name='topicmod_projects_ldawn.WordNetFile.Synset.hyperparameter', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_WORDNETFILE_SYNSET_WORD, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=140,
  serialized_end=486,
)

_WORDNETFILE = descriptor.Descriptor(
  name='WordNetFile',
  full_name='topicmod_projects_ldawn.WordNetFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='synsets', full_name='topicmod_projects_ldawn.WordNetFile.synsets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='root', full_name='topicmod_projects_ldawn.WordNetFile.root', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_WORDNETFILE_SYNSET, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=486,
)

_WORDNETFILE_SYNSET_WORD.containing_type = _WORDNETFILE_SYNSET;
_WORDNETFILE_SYNSET.fields_by_name['words'].message_type = _WORDNETFILE_SYNSET_WORD
_WORDNETFILE_SYNSET.containing_type = _WORDNETFILE;
_WORDNETFILE.fields_by_name['synsets'].message_type = _WORDNETFILE_SYNSET
DESCRIPTOR.message_types_by_name['WordNetFile'] = _WORDNETFILE

class WordNetFile(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Synset(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    
    class Word(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _WORDNETFILE_SYNSET_WORD
      
      # @@protoc_insertion_point(class_scope:topicmod_projects_ldawn.WordNetFile.Synset.Word)
    DESCRIPTOR = _WORDNETFILE_SYNSET
    
    # @@protoc_insertion_point(class_scope:topicmod_projects_ldawn.WordNetFile.Synset)
  DESCRIPTOR = _WORDNETFILE
  
  # @@protoc_insertion_point(class_scope:topicmod_projects_ldawn.WordNetFile)

# @@protoc_insertion_point(module_scope)
